name: rtg_app
description: Rtg app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^6.1.3
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter 
  intl: ^0.17.0
  sembast: ^3.2.0+1
  path_provider: ^2.0.11
  path: ^1.8.1
  toast: ^0.1.5
  flutter_easyloading: ^3.0.5
  http: ^0.13.4
  sprintf: ^6.0.0
  uuid: any
  edit_distance: ^0.4.1
  fraction: ^4.1.1
  wakelock: ^0.6.1+2
  carousel_slider: ^4.1.1
  share_plus: ^4.0.9
  flutter_dotenv: ^5.0.2
  pdf: ^3.8.1
  printing: ^5.9.1

dev_dependencies:
  # flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

  mockito:

  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/images/
    - assets/.env
    - assets/test_driver.env

  fonts:
  - family: RtgAppIcons
    fonts:
      - asset: assets/fonts/RtgAppIcons.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/rtg_app_icon.png"
  image_path_android: "assets/launcher/rtg_app_icon.png"
  adaptive_icon_background: "assets/launcher/rtg_app_icon_background.png"
  adaptive_icon_foreground: "assets/launcher/rtg_app_icon_foreground.png"


